/*

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

*/

class Solution {
public:
    char findTheDifference(string s, string t) {
    char di = 'a';
    int a[26],b[26];
    for (int i = 0;i<26;++i)
    {
        a[i] = 0;
        b[i] = 0;
    }
    for (int i = 0;i<s.size();++i)
        a[s[i]-'a']++;
    for (int i = 0;i<t.size();++i)
        b[t[i]-'a']++;

    for (int i = 0;i<26;)
    {
        if (a[i] == b[i])
            ++i;
        else
        {
            di = 'a' + i;
            break;
        }
    }
    return di;
}
};
